#!/bin/perl
# -*- Perl -*-

#
# Globals
#
use vars qw/ %opt /;

my $ksldg = "ksldg";

#
# Command line options processing
#
sub init()
{
    use Getopt::Std;
    $Getopt::Std::STANDARD_HELP_VERSION = true;
    usage() if $#ARGV == -1;
    my $opt_string = 'hecad:n:p:rt:is:';
    getopts( "$opt_string", \%opt ) or usage();
    usage() if $opt{h};
}

#
# Message about this program and how to use it
#
sub usage()
{
  print << "EOF";

Data Generator for Skyline for feeding PostgreSQL psql

usage: $0 [-hecadnrti] -- [OPTIONS FOR $ksldg]

 -h,  --help    print this help and exit.
 --version      display the version of $0 and exit.

 -e|-c|-a       distribution
 -d DIM         dimensions
 -n NUMBER      number of vectors
 -s SEED        seed random generator to SEED
 -p PAD         add PAD long varchar for padding
 -r             (re)create table
 -t TABLE       override default table name (e|c|a)DIMdNUMBER[sSEED][pPAD]
 -i             unique id for every vector

Options for $ksldg: see $ksldg -h

example: $0 -e -d 3 -n 100 | psql postgres

EOF
    exit;
}


sub HELP_MESSAGE()
{
  usage();
}

sub VERSION_MESSAGE()
{
  print << "EOF";
$0 version 1.0
EOF
  exit();
}

init();

die "$0: error: you must spec. exactly one distribution, stopped at" if ($opt{e} + $opt{c} + $opt{a} != 1);
die "$0: error: you must spec. the number of vectors, stopped at" if ($opt{n} eq "");

$header=1;
$id = 1;
$prefix = "";
$suffix = "";
$dist = $opt{e} ? "e" : $opt{c} ? "c" : $opt{a} ? "a" : "?";
$dim = $opt{d};
$n = $opt{n};
$pad = $opt{p};

if ($opt{s} ne "") {
  $seed = "-s $opt{s}";
}

$ksldg_args = join(" ", "-$dist", "-d $dim", "-n $n", $seed, @ARGV);

die "$0: error: you must spec. the number of dimensions, stopped at" if ($dim < 1);


$table = "$dist${dim}d$n";

if ($opt{s} ne "") {
  $table = $table . "s$opt{s}";
}

if ($pad) {
  $table = $table . "p${pad}";
  $suffix = ";\"" . ("X" x $pad) . "\"";
}

if ($opt{t} ne "") {
  $table = $opt{t};
}

die "$0: you must spec. a table name" if ($table eq "");

open(KSLDG, "$ksldg $ksldg_args |") || die "can't fork: $!";
while ($line = <KSLDG>) {
  if ($header == 1) {
    @fields = split(/ /, $line);
    $dim = $#fields + 1;

    push @flds, "id" if ($opt{i});
    push @defs, "id int" if ($opt{i});

    for ($i=1; $i<=$dim; $i++) {
      push @flds, "d$i";
      push @defs, "d$i float";
    }

    push @flds, "pad${pad}" if ($opt{p});
    push @defs, "pad${pad} varchar(${pad})" if ($opt{p});

    if ($opt{r}) {
      print "drop table if exists $table;\n";
      print "create table $table (", join(", ", @defs), ");\n";
    }

    print "copy $table(", join(", ", @flds), ") from stdin delimiters ';' csv quote '\"';\n";
    $header = 0;
  }

  if ($opt{i}) {
    $prefix = "$id;";
    $id++;
  }

  $line =~ s/ /;/g;
  chomp $line;

  print "$prefix$line$suffix\n";
}
close KSLDG || die "bad $ksldg: $! $?";
print "\\.\n";
