#!/bin/bash



for dist in indep corr anit; do
for dim in 2 3 5 10 15; do
for n in 100 1000 10000 100000; do
for method in bnl sfs; do
for rep in 1 2 3 4 5 6; do

./pg_slprofile --maxdim=15 --dim=$dim --dist=$dist --rows=$n --method=$method --run="$method.$dist.$dim.$n.$rep"

done
done
done
done
done


#./pg_slprofile -n 100000 -d 4 --method=bnl  -run="sd.12"