#!/bin/perl -w
# -*- Perl -*- tell emacs it's a perl file

# Author: Hannes Eder <Hannes@HannesEder.net>

use strict;
use Getopt::Long;
use Text::CSV;

my @columns = ();
my $show_header = 1;
my @headers = ();

my $result = GetOptions("column|c=s" => \@columns,
			"header!" => \$show_header);

die "error: couldn't parse options, stopped at : " if (!$result);

for (my $i=0; $i <= $#columns; ++$i) {
    my $column = $columns[$i];
    if ($column =~ m/^([^=]+)=([^=]+)$/) {
	$columns[$i] = $1;
	$headers[$i] = $2;
    }
    else {
	$headers[$i] = $column;
    }
}

print join(";", map { "\"$_\""; } ("runid", @headers)), "\n" if ($show_header);

exit 0;

my $cur_runid = "";
my $runid;
my $name;
my $value;

my $csv = Text::CSV->new({always_quote => 1});

my %values = ();


sub output()
{
    my @outfields = ();
    push @outfields, $cur_runid;

    for my $column (@columns) {
	my $v = $values { $column };
	push @outfields, defined($v) ? $v : "";
    }

    if ($csv->combine(@outfields)) {
	print $csv->string(), "\n";
    }
}

my $line;

while (defined($line = <>)) {
    chomp $line;
    next if ($line =~ m/^#/);

    if ($csv->parse($line)) {
	my @fields = $csv->fields;

	die "error: csv file must have 3 fields (runid, name, value), stopped at " if ($#fields != 2);
	my ($runid, $name, $value) = @fields;

	if ($runid ne $cur_runid) {
	    if ($cur_runid) {
		# output values
		output();
	    }
	    
	    %values = ();

	    $cur_runid = $runid;
	}

	$values{ $name } = $value;
    }
    else {
	my $err = $csv->error_input;
	die "error: CSV parse failed on argument: ${err}, stopped at ";
    }
}

output() if ($cur_runid);
